[application]

[web.app]

# HTML title tag content
title = "cat_tongue"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "org.omusubi.aki"
publisher = "aki.akaguma"
icon = ["resources/cat.png"]
#icon = ["assets/icon.png"]
#resource = [""]
#copyright = ""
category = "desktop"
short_description = "a modified dioxus sample."
long_description = "This is a modified version of the Dioxus sample hot_dog."
deb = { section = "AAA-desktop", priority = "optional", files = {} }

#[bundle.deb]
#section = "AAA-desktop"
#priority = "optional"

